apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: instagram_clone_frontend_hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: instagram_clone_frontend_deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
        
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: instagram_clone_backend_hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: instagram_clone_backend_deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
        
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70