apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: instagram-clone-frontend-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: instagram-clone.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: instagram-clone-frontend-service
            port:
              number: 80