apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: instagram_clone_frontend_ingress
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: instagram_clone.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: instagram_clone_frontend_service
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: instagram_clone_prometheus
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: instagram_clone.prometheus.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-prometheus
            port:
              number: 9090

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: instagram_clone_grafana
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: instagram_clone.grafana.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80