apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
labels:
  - includeSelectors: true
    pairs:
      app: instagram-clone

resources:
  - deployment.yaml
  - hpa.yaml
  # - vpa.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - pvc.yaml
  - sc.yaml
  - svc.yaml
  - pdb.yaml
  - monitoring.yaml

configMapGenerator:
  - name: instagram-clone-config
    envs:
      - configs.env

secretGenerator:
  - name: instagram-clone-secret
    envs:
      - secrets.env