apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: instagram-clone-backend-monitor
  labels:
    release: kube-prometheus-stack   # must match Prometheus operator's selector
spec:
  selector:
    matchLabels:
      app: instagram-clone
      tier: backend
  namespaceSelector:
    matchNames:
    - dev
  endpoints:
  - port: "instagram-clone-backend-service-port"
    path: /metrics
    interval: 30s