apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: instagram-clone-frontend-pdb
  namespace: dev
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: instagram-clone
      tier: frontend

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: instagram-clone-backend-pdb
  namespace: dev
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: instagram-clone
      tier: backend