apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instagram_clone_frontend_pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: instagram_clone_sc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instagram_clone_backend_pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: instagram_clone_sc