apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instagram-clone-frontend-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: instagram-clone-sc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instagram-clone-backend-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: instagram-clone-sc