apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: instagram_clone_sc
provisioner: kubernetes.io/no-provisioner # Local
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
mountOptions:
  - discard # this might enable UNMAP / TRIM at the block storage layer
volumeBindingMode: WaitForFirstConsumer
